#!/usr/bin/env bash
#
# This file is part of Flask-Wiki
# Copyright (C) 2025 RERO
#
# Flask-Wiki is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

# COLORS for messages
NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

PROGRAM=`basename $0`
SCRIPT_PATH=$(dirname "$0")

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

success_msg+exit() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}" && exit 0
}

pip_audit_exceptions=""
add_exceptions() {
  pip_audit_exceptions="$pip_audit_exceptions --ignore-vuln $1"""
}

# Displays program name
msg "PROGRAM: ${PROGRAM}"

# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via uv command:\n\t${PROGRAM}"
fi

function pretests () {
  info_msg "Check vulnerabilities:"
  # py 1.11.0  PYSEC-2022-42969
  add_exceptions " PYSEC-2022-42969"
  pip-audit ${pip_audit_exceptions}

  info_msg "Test formatting:"
  ruff format . --check
  info_msg "Test linting:"
  ruff check
}

function tests () {
  info_msg "Tests:"
  pytest
}

if [ $# -eq 0 ]
  then
    set -e
    pretests
    # TODO: Uncomment when there is at least one test
    # tests
fi

success_msg+exit "Perfect ${PROGRAM} external! See you soon…"
