name: run tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Code Quality
      run: poetry run black . --check

    - name: Run Tests
      run: poetry run pytest

    - name: Test publish in dry run mode
      run: poetry publish --build --dry-run
